#!/usr/bin/env python3
"""
Local Growth — SMB Social Media Content Fabricator
Watches a job_photos folder, sends images to local Ollama vision model,
generates social media captions, builds a 30-day content calendar.
"""

import json
import os
import glob
import base64
from datetime import datetime, timedelta

import requests

PHOTOS_DIR = "./job_photos"
CALENDAR_JSON = "content_calendar.json"
CALENDAR_MD = "content_calendar.md"
OLLAMA_URL = "http://localhost:11434/api/generate"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def get_image_files():
    """Find all image files in job_photos folder."""
    os.makedirs(PHOTOS_DIR, exist_ok=True)
    files = []
    for f in os.listdir(PHOTOS_DIR):
        if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS:
            files.append(os.path.join(PHOTOS_DIR, f))
    return sorted(files)


def generate_captions(image_path):
    """Send image to local Ollama vision model for social media captions."""
    with open(image_path, "rb") as f:
        image_b64 = base64.b64encode(f.read()).decode("utf-8")

    prompt = (
        "You are a social media manager for a local trades/contractor business. "
        "Write 3 social media post captions for this job photo. "
        "Make them engaging, professional, and local-community focused. "
        "Include relevant hashtags. Format as:\n"
        "POST 1: [caption]\n"
        "POST 2: [caption]\n"
        "POST 3: [caption]"
    )

    try:
        resp = requests.post(OLLAMA_URL, json={
            "model": "moondream",
            "prompt": prompt,
            "images": [image_b64],
            "stream": False,
        }, timeout=120)

        if resp.status_code == 200:
            return resp.json().get("response", "No captions generated.")
        return None
    except requests.ConnectionError:
        return None
    except Exception as e:
        print(f"    [Error: {e}]")
        return None


def parse_captions(raw_text):
    """Parse numbered captions from model output."""
    captions = []
    for line in raw_text.strip().split("\n"):
        line = line.strip()
        for prefix in ["POST 1:", "POST 2:", "POST 3:", "1.", "2.", "3."]:
            if line.upper().startswith(prefix.upper()):
                caption = line[len(prefix):].strip()
                if caption:
                    captions.append(caption)
                break
    # Fallback: if parsing failed, split by double newlines
    if not captions and raw_text.strip():
        captions = [p.strip() for p in raw_text.strip().split("\n\n") if p.strip()][:3]
    return captions


def build_content_calendar(all_content):
    """Build a 30-day content calendar from generated posts."""
    calendar = []
    start_date = datetime.now()

    # Flatten all captions
    all_posts = []
    for entry in all_content:
        for caption in entry["captions"]:
            all_posts.append({
                "caption": caption,
                "source_photo": entry["photo"],
            })

    # Distribute across 30 days
    for i in range(30):
        date = start_date + timedelta(days=i)
        day_entry = {
            "date": date.strftime("%Y-%m-%d"),
            "day": date.strftime("%A"),
            "posts": [],
        }
        if all_posts:
            post = all_posts.pop(0)
            day_entry["posts"].append(post)
            # Recycle if we run out
            all_posts.append(post)
        calendar.append(day_entry)

    return calendar


def write_calendar_md(calendar):
    """Generate a markdown content calendar."""
    lines = [
        "# 30-Day Social Media Content Calendar",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
    ]

    for day in calendar:
        lines.append(f"## {day['date']} ({day['day']})")
        if day["posts"]:
            for post in day["posts"]:
                lines.append(f"- **Post:** {post['caption']}")
                lines.append(f"  - *Photo:* `{post['source_photo']}`")
        else:
            lines.append("- *No post scheduled*")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Local Growth on {datetime.now().isoformat()}*")

    return "\n".join(lines)


def main():
    print("=" * 60)
    print("  Local Growth — SMB Social Media Content Fabricator")
    print("=" * 60)

    images = get_image_files()
    if not images:
        print(f"\n  No images found in {PHOTOS_DIR}/")
        print(f"  Supported: {', '.join(IMAGE_EXTENSIONS)}")
        print(f"  Place job photos in {PHOTOS_DIR}/ and run again.")
        return

    print(f"\n  Found {len(images)} image(s) to process.\n")

    all_content = []

    for i, img in enumerate(images, 1):
        filename = os.path.basename(img)
        print(f"  [{i}/{len(images)}] {filename}...", end=" ", flush=True)

        raw = generate_captions(img)
        if raw:
            captions = parse_captions(raw)
            print(f"{len(captions)} captions generated")
            all_content.append({
                "photo": filename,
                "captions": captions,
                "raw_response": raw,
                "generated_at": datetime.now().isoformat(),
            })
        else:
            print("Ollama not available — using placeholder")
            all_content.append({
                "photo": filename,
                "captions": [
                    f"Another great job completed! Check out our latest work. #LocalBusiness #QualityWork",
                    f"We take pride in every project, big or small. Call us today! #TradesLife",
                    f"Your trusted local professionals. See what we've been up to! #CommunityFirst",
                ],
                "generated_at": datetime.now().isoformat(),
            })

    # Save content calendar JSON
    with open(CALENDAR_JSON, "w") as f:
        json.dump(all_content, f, indent=2)
    print(f"\n  Content saved to {CALENDAR_JSON}")

    # Build 30-day calendar
    calendar = build_content_calendar(all_content)
    md_content = write_calendar_md(calendar)

    with open(CALENDAR_MD, "w") as f:
        f.write(md_content)
    print(f"  30-day calendar saved to {CALENDAR_MD}")

    # Summary
    total_posts = sum(len(e["captions"]) for e in all_content)
    print(f"\n  Summary: {total_posts} posts from {len(images)} photos")
    print(f"  Content calendar covers {len(calendar)} days")


if __name__ == "__main__":
    main()
