#!/usr/bin/env python3
"""
SOP Vision — Auto-Documentation Worker (Video -> PDF SOP)
Extracts frames from a repair video, describes each via local Ollama vision model,
assembles into a Standard Operating Procedure document.
"""

import json
import os
import subprocess
import sys
import glob
from datetime import datetime

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
FRAMES_DIR = "./sop_frames"
OUTPUT_MD = "FINAL_SOP.md"
OUTPUT_PDF = "FINAL_SOP.pdf"


def extract_frames(video_path, fps=1):
    """Extract frames at specified FPS using ffmpeg."""
    os.makedirs(FRAMES_DIR, exist_ok=True)

    # Clear old frames
    for old in glob.glob(os.path.join(FRAMES_DIR, "frame_*.jpg")):
        os.remove(old)

    cmd = [
        "ffmpeg", "-i", video_path,
        "-vf", f"fps={fps}",
        "-q:v", "2",
        os.path.join(FRAMES_DIR, "frame_%04d.jpg"),
        "-y",  # overwrite
    ]

    print(f"  Extracting frames at {fps} FPS...")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            print(f"  [ERROR] ffmpeg failed: {result.stderr[:200]}")
            return []
    except FileNotFoundError:
        print("  [ERROR] ffmpeg not found. Install with: sudo apt install ffmpeg")
        return []

    frames = sorted(glob.glob(os.path.join(FRAMES_DIR, "frame_*.jpg")))
    print(f"  Extracted {len(frames)} frames.")
    return frames


def describe_frame_with_ollama(frame_path, frame_number):
    """Send frame to local Ollama vision model for description."""
    import base64

    with open(frame_path, "rb") as f:
        image_b64 = base64.b64encode(f.read()).decode("utf-8")

    prompt = (
        "You are documenting a repair procedure. Describe what is happening in this image: "
        "What tools are visible? What action is being performed? What component is being worked on? "
        "Be specific and concise (2-3 sentences)."
    )

    try:
        resp = requests.post(OLLAMA_URL, json={
            "model": "moondream",
            "prompt": prompt,
            "images": [image_b64],
            "stream": False,
        }, timeout=120)

        if resp.status_code == 200:
            return resp.json().get("response", "No description available.")
        return f"[Model returned status {resp.status_code}]"
    except requests.ConnectionError:
        return "[Ollama not available — install and run: ollama serve]"
    except Exception as e:
        return f"[Error: {e}]"


def build_sop(video_name, descriptions):
    """Assemble frame descriptions into a markdown SOP."""
    lines = [
        f"# Standard Operating Procedure",
        f"## Source: {video_name}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Total Steps:** {len(descriptions)}",
        "",
        "---",
        "",
    ]

    for i, (frame_file, desc) in enumerate(descriptions, 1):
        lines.append(f"### Step {i}")
        lines.append(f"**Frame:** `{os.path.basename(frame_file)}`")
        lines.append(f"**Timestamp:** ~{i} second(s)")
        lines.append("")
        lines.append(desc)
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.extend([
        "## Safety Notes",
        "- Always wear appropriate PPE for the task.",
        "- Ensure equipment is powered off before servicing.",
        "- Follow lockout/tagout procedures.",
        "",
        f"*Generated by SOP Vision on {datetime.now().isoformat()}*",
    ])

    return "\n".join(lines)


def convert_to_pdf(md_content):
    """Attempt to convert markdown to PDF using weasyprint."""
    try:
        from weasyprint import HTML
        import markdown

        html_content = f"""
        <html><head><style>
            body {{ font-family: sans-serif; padding: 40px; line-height: 1.6; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #34495e; }}
            h3 {{ color: #2980b9; }}
            hr {{ border: 1px solid #bdc3c7; }}
            code {{ background: #ecf0f1; padding: 2px 6px; border-radius: 3px; }}
        </style></head><body>{markdown.markdown(md_content)}</body></html>
        """

        HTML(string=html_content).write_pdf(OUTPUT_PDF)
        return True
    except ImportError:
        return False
    except Exception as e:
        print(f"  [PDF Error] {e}")
        return False


def main():
    print("=" * 60)
    print("  SOP Vision — Auto-Documentation Worker")
    print("  Video -> Markdown/PDF Standard Operating Procedure")
    print("=" * 60)

    if len(sys.argv) < 2:
        print("\n  Usage: python sop_vision.py <video_file>")
        print("  Example: python sop_vision.py repair_demo.mp4")
        print("\n  Requirements:")
        print("    - ffmpeg installed (sudo apt install ffmpeg)")
        print("    - Ollama running with moondream model")
        print("      ollama pull moondream && ollama serve")
        return

    video_path = sys.argv[1]
    if not os.path.exists(video_path):
        print(f"\n  [ERROR] Video not found: {video_path}")
        return

    video_name = os.path.basename(video_path)
    print(f"\n  Processing: {video_name}")

    # Step 1: Extract frames
    frames = extract_frames(video_path)
    if not frames:
        print("  No frames extracted. Check ffmpeg and video file.")
        return

    # Step 2: Describe each frame with vision model
    print(f"\n  Describing {len(frames)} frames with Ollama vision model...")
    descriptions = []
    for i, frame in enumerate(frames, 1):
        print(f"  [{i}/{len(frames)}] {os.path.basename(frame)}...", end=" ", flush=True)
        desc = describe_frame_with_ollama(frame, i)
        descriptions.append((frame, desc))
        print("done")

    # Step 3: Build SOP markdown
    print("\n  Building SOP document...")
    md_content = build_sop(video_name, descriptions)

    with open(OUTPUT_MD, "w") as f:
        f.write(md_content)
    print(f"  Saved: {OUTPUT_MD}")

    # Step 4: Attempt PDF conversion
    print("  Attempting PDF conversion...")
    if convert_to_pdf(md_content):
        print(f"  Saved: {OUTPUT_PDF}")
    else:
        print(f"  PDF conversion not available (install weasyprint + markdown).")
        print(f"  Markdown SOP is ready: {OUTPUT_MD}")

    print(f"\n  SOP generation complete! {len(descriptions)} steps documented.")


if __name__ == "__main__":
    main()
